### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by edrevo** [tonistiigi/dockerfile#1]
Hi @tonistiigi! Thanks for the great work on buildkit 👏  What is the license for this project? Can I fork it and evolve it?

**Comment by tonistiigi** [comment]
The development of this code moved to https://github.com/moby/buildkit/tree/master/frontend/dockerfile and that is the place where `tonistiigi/dockerfile` image is built. I should probably remove this repo for now so it isn't confusing.

**Comment by AkihiroSuda** [comment]
s/remove/archive/ ?

**Comment by edrevo** [comment]
Thanks for the info! If you indeed remove this repo, it would be good to add the link you provided in the Dockerhub's `tonistiigi/dockerfile` page. I'm guessing I'm not the only one with an interest in extending the syntax of Dockerfile :)
